services:
  - type: web
    name: result-automation-api
    env: docker
    region: oregon
    plan: free
    branch: main
    rootDir: /
    healthCheckPath: /docs
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        value: "postgresql://result_automation_user:LrwTETINmsLvvXGHPEGLxTHWx5XFLU0K@dpg-cup6qfl6l47c73cjd290-a.oregon-postgres.render.com/result_automation"
